# Generated by Django 4.1.2 on 2022-10-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants'),
        ),
    ]
